import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

export const originalHash = '6b21281d11d84690d2bbf993b3ac3c0ba6c64cd38bfb4e5dc897443752ee9d23';
const source = readFileSync(new URL('../f4fchecker.js', import.meta.url));
if (createHash('sha256').update(source).digest('hex') !== originalHash) {
  throw new Error('The original checker changed. Restore it before building.');
}
// The complete original file is embedded verbatim, without editing its IIFE.
// Returning that IIFE lets the adapter await its genuine execution boundary.
const runner = Buffer.concat([
  Buffer.from('// Generated by scripts/build.mjs. Do not edit.\nvoid F4FAdapter.run(async ({ document, alert }) => {\nreturn '),
  source,
  Buffer.from('\n});\n')
]);
writeFileSync(new URL('../extension/checker-runner.js', import.meta.url), runner);
console.log('Built the extension runner; original checker SHA-256 verified.');
